name: Deploy to Server

on:
  push:
    branches:
      - main  # mainブランチに保存された時に実行されます

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # サブアカウントの接続先が既に「kids-log」フォルダになっている場合、
          # 「./」を指定することで、そのフォルダの中に直接ファイルが書き込まれます。
          server-dir: ./ 
          local-dir: ./dist/
